---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.email.test: |
    host: tr2-mailgw03.prod.achievers.com
    port: 25
    from: shivam.sood@achievers.com
  template.app-sync-succeeded: |
    email:
      subject: Application one has been successfully synced.
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application two has been successfully synced at three.
      Sync operation details are available at: four .

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations: 
    notifications.argoproj.io/subscribe.on-sync-succeeded.test: "shivam.sood@achievers.com"
  name: helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
