---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret1
stringData:
  channel-teams-url: https://achieversllc.webhook.office.com/webhookb2/e1c36f55-b4a6-4fcc-b63d-9c6d4d4fc1cb@8bd0082d-d958-423a-821f-dd0f22a1b519/IncomingWebhook/4cc501d15f364e2dace7f8972c2f89eb/3629f90a-a966-4ac3-a8ec-6c8b9dbc8d6a

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm1
data:
  service.webhook.testhook: |
    url: https://achieversllc.webhook.office.com/webhookb2/e1c36f55-b4a6-4fcc-b63d-9c6d4d4fc1cb@8bd0082d-d958-423a-821f-dd0f22a1b519/IncomingWebhook/4cc501d15f364e2dace7f8972c2f89eb/3629f90a-a966-4ac3-a8ec-6c8b9dbc8d6a
  template.app-sync-succeeded: |
    webhook:
      testhook:
        method: POST 
        body: |     
          {
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "0076D7",
            "summary": "one sync status is two",
            "sections": [
              {
                "activityTitle": "three sync status is four",
                "facts": [
                  {
                    "name": "Synced at",
                    "value": "5"
                  },
                  {
                    "name": "Sync status",
                    "value": "6"
                  }
                ],
                "markdown": true
              }
            ],
            "potentialAction": [
              {
                "@type": "OpenUri",
                "name": "Details",
                "targets": [
                  {
                    "os": "default",
                    "uri": "eight/applications/seven?operation=true"
                  }
                ]
              }
            ]
          } 

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.webhook: ""
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
