# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: argocd-notifications-secret
# stringData:
#   channel-teams-url: https://achieversllc.webhook.office.com/webhookb2/e1c36f55-b4a6-4fcc-b63d-9c6d4d4fc1cb@8bd0082d-d958-423a-821f-dd0f22a1b519/IncomingWebhook/4cc501d15f364e2dace7f8972c2f89eb/3629f90a-a966-4ac3-a8ec-6c8b9dbc8d6a
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: argocd-notifications-cm
# data:
#   service.teams: |
#     recipientUrls: 
#       channelName: $channel-teams-url
---
apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: msteams-notification
      image: curlimages/curl
      command: "curl -H 'Content-Type: application/json' -d '{'summary':'Deployment','sections':[{'activityTitle':'<b>Deployment - [ stg ][ {{ build.status }} ]</b>','activitySubtitle':'Deployment for {{ repo.name }} - #{{ build.number }}','activityImage':'https://luktom.net/wordpress/wp-content/uploads/2019/11/argo.png'},{'title':'Details:','facts':[{'name':'Application','value':'{{ repo.name }}'},{'name':'Sync Status','value':'{{.app.status.sync.status}}'},{'name':'Synced at','value':'{{.app.status.operationState.finishedAt}}'},{'name':'Repository','value':'{{.app.spec.source.repoURL}}'}]}],'potentialAction':[{'@context':'http://schema.org','@type':'ViewAction','name':'View in ArgoCD','target':['{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true']}]}' https://achieversllc.webhook.office.com/webhookb2/e1c36f55-b4a6-4fcc-b63d-9c6d4d4fc1cb@8bd0082d-d958-423a-821f-dd0f22a1b519/IncomingWebhook/0ef8db7a0272491ba415c9537b35ff17/3629f90a-a966-4ac3-a8ec-6c8b9dbc8d6a" 
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: channelName
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: prometheus
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 13.0.2
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
